### ISSUE TITLE
Missing schedule for current season

### ISSUE THREAD

**Issue by fhs** [ecopony/gamedayapi#1]
Schedules directory is missing files for years 2016, 2017 and 2018. It's not clear to me where those files can be obtained.

**Comment by ecopony** [comment]
Hi Fazlul -- I'm not sure how I missed your comment. Apologies for the 2+ year delay! You probably don't need this anymore, but the schedules come from Retrosheet: https://www.retrosheet.org/schedule/ 

I'll update the docs with that info.
